version: 1

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
  EE_BUILDER_IMAGE: "aap-hub.openshift-vms.svc.cluster.local/ansible-automation-platform-21/ansible-builder-rhel8:latest"
  EE_BASE_IMAGE: "aap-hub.openshift-vms.svc.cluster.local/ansible-automation-platform-21/ee-minimal-rhel8:latest"

ansible_config: 'ansible.cfg' 

dependencies: 
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps: 
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN curl "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/latest/openshift-client-linux.tar.gz" -o /tmp/oc.tar.gz
    - RUN tar xvzf /tmp/oc.tar.gz -C /tmp/
    - RUN ls -l /tmp/
    - RUN mv /tmp/oc /tmp/kubectl /usr/bin
    - RUN oc version
    - RUN rm -rf /tmp/oc.tar.gz
