version: 1

build_arg_defaults: 
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-v"
  EE_BASE_IMAGE: "registry.redhat.io/ansible-automation-platform-20-early-access/ee-minimal-rhel8"

ansible_config: 'ansible.cfg' 

dependencies: 
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps: 
  prepend: |
    RUN whoami
    RUN cat /etc/os-release
  append:
    - RUN echo This is a post-install command!
    - RUN ls -la /etc
