apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: example-task
  namespace: dm-pipeline
spec:
  params:
    - name: appName
      type: string
  steps:
    - image: registry.redhat.io/ubi7/ubi-minimal
      command:
        - /bin/bash
      args:
        - '-c'
        - echo
        - $(inputs.params.appName)