---
- name: Apply system-role
  hosts: "{{ host_target }}"
  become: true
  collections:
    - redhat.rhel_system_roles

  tasks:

    - when: firewall_enable == 'yes'
      name: Install and enable firewalld
      include_role:
        name: redhat.rhel_system_roles.firewall
      vars:
        firewall:
          service: "{{ firewall_service }}"
          state: enabled

