apiVersion: ndb.nutanix.com/v1alpha1
kind: Database
metadata:
  # This name that will be used within the kubernetes cluster
  name: demodavid
  #namespace: demo
spec:
  # NDB server specific details
  ndb:
    # Cluster id of the cluster where the Database has to be provisioned
    # Can be fetched from the GET /clusters endpoint
    clusterId: "2be090fc-e358-4447-ab9e-95b2af977176" 
    # Credentials secret name for NDB installation
    # data: username, password, 
    # stringData: ca_certificate
    credentialSecret: ndb-secret
    # The NDB Server
    server: https://10.6.114.56:8443/era/v0.9
    # Set to true to skip SSL verification, default: false.
    skipCertificateVerification: true
  # Database instance specific details (that is to be provisioned)
  databaseInstance:
    # The database instance name on NDB
    databaseInstanceName: "psql01"
    # Names of the databases on that instance
    databaseNames:
      - FRUITSDB
    # Credentials secret name for NDB installation
    # data: password, ssh_public_key
    credentialSecret: db-secret
    size: 10
    timezone: "CET"
    type: postgres