apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pacman-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: apps-demo
    server: https://kubernetes.default.svc
  project: apps-demo
  source:
    path: openshift/demos/ocp-argocd-apps/apps/pacman
    repoURL: https://github.com/davmartini/redhat-techs.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
    - CreateNamespace=true