apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: googleidp 
    mappingMethod: claim 
    type: Google
    google:
      clientID: 106565764394-4iu6ms4pjds728d5qcicf8v8nphnepfc.apps.googleusercontent.com
      clientSecret:
        name: google-secret
      hostedDomain: "redhat.com" 
