---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mix-app
  name: mix-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: mix-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mix-app
    spec:
      containers:
      - image: registry.connect.redhat.com/haproxytech/haproxy
        name: haproxy
        resources: {}
---