kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  annotations:
  name: postgresql-db
  labels:
    app: postgresql-db
    app.kubernetes.io/component: postgresql-db
    app.kubernetes.io/instance: postgresql-db
    app.kubernetes.io/part-of: fruit-service-app
    app.openshift.io/runtime: postgresql
spec:
  strategy:
    type: Rolling
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 600
      maxUnavailable: 25%
      maxSurge: 25%
    resources: {}
    activeDeadlineSeconds: 21600
  triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - postgresql
        from:
          kind: ImageStreamTag
          namespace: openshift
          name: 'postgresql:10-el8'
  replicas: 1
  revisionHistoryLimit: 10
  test: false
  selector:
    deploymentconfig: postgresql-db
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploymentconfig: postgresql-db
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: postgresql
          ports:
            - containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRESQL_DATABASE
              value: FRUITSDB
            - name: POSTGRESQL_PASSWORD
              value: secret
            - name: POSTGRESQL_USER
              value: luke
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler