apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quarkus-app-with-bdd-on-ocp
  namespace: demo
spec:
  project: default
  source:
    repoURL: 'https://github.com/davmartini/redhat-techs.git'
    path: openshift/demos/ocp-crud/with-ocp-bdd/gitops/
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo