---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ndb-users
rules:
  - verbs:
      - get
      - watch
      - list
      - create
      - delete
    apiGroups:
      - 'ndb.nutanix.com'
    resources:
      - databases
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ndb-users
subjects:
  - kind: Group
    name: users
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ndb-users
