apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
  name: idm-ldap
  namespace: openshift-vms
  labels:
    app: idm-ldap
    os.template.kubevirt.io/rhel8.5: 'true'
    vm.kubevirt.io/template: dm-rhel8-template
    vm.kubevirt.io/template.namespace: openshift-vms
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.16.4
    workload.template.kubevirt.io/server: 'true'
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: idm-ldap-rootdisk-120en
        namespace: openshift-vms
      spec:
        source:
          pvc:
            name: dm-rhel8-template-rootdisk
            namespace: openshift-vms
        storage:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi
          storageClassName: local-disks
          volumeMode: Filesystem
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: small
        vm.kubevirt.io/os: rhel8
        vm.kubevirt.io/workload: server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: idm-ldap
        kubevirt.io/size: small
        os.template.kubevirt.io/rhel8.5: 'true'
        vm.kubevirt.io/name: idm-ldap
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - disk:
                bus: virtio
              name: cloudinitdisk
            - bootOrder: 1
              disk:
                bus: virtio
              name: rootdisk
          interfaces:
            - macAddress: ''
              masquerade: {}
              model: virtio
              name: nic-0
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel8.4.0
        resources:
          requests:
            memory: 2Gi
      evictionStrategy: LiveMigrate
      hostname: idm-ldap
      networks:
        - name: nic-0
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              user: cloud-user
              password: ''
              chpasswd:
                expire: false
              ssh_authorized_keys:
                - >-
                  ssh-rsa
                  AAAAB3NzaC1yc2EAAAADAQABAAABgQCeKuohg3lPzDeeQBqXrllzylbJEDrVg9bbpGaYeLfTQ1ibAXpU6PDwOvweHvzBRleW/39Y4t2pF0T6DiQgymapIuRFIXqJR6qKRB6GUdJgLzV4q5IJFmDJFE3XO9TS24N4stjzvNiOH/LNjN5mVHKLorO7qIPS9O3eRi66Bkqsj6Wg8NLI8ufGCBeBXu/rcnDW2phyoKvSrXl0vYNc+nSCGYNU/Fmh6hpomtm/6h+9A3ep6SOyC8RepId1kF3IXLyQpbFXEGDmcbxUgH2FQnsBe+M62rYU0lP/c7wEdWRvYX0c17ZFeg65D9DW8u8Ya33PeicgH4N4ooKGTb5Uekj54OGYnxrlwP+gXTJNk8IYd3UgdYNZTzvHKb9YMHY1Z11kYaQWi6YZwxazCoH/KIADCMzbKnayZAiwgOTVi2jP2JQvEGe+TAoYLKM1Gr9pEQC9yZImArBmw3w50yI1ZiKy+DgygolZYeGhYixGU1jePujMUgGw5EaoZzrJ9gbz47c=
                  dmartini@Davids-MacBook-Pro
                - >-
                  ssh-rsa
                  AAAAB3NzaC1yc2EAAAADAQABAAABgQC3OL8vJoTsbn/LBUZWgV8YYmxUZSMAWZ6UKMHC2iF9VCYmuI0opJKNBpEDFlomrENOm7HkEIafdPpFfEiDMszDhskvNWAVPiJJChjMBxFgvNWLAEHJQKvGaylVDF4yOex9ehMKOnhBVnO7FFrn33AmgiikEQRcqkz9Q1NQ7ccDZzF5eml0brxmO+2IziUrPdeVwkR7Wzw19zyxLf3f7dfGkfnfoeku1D8BWQaclN0T8AAC4IAVQ1YXp5kf4rpPdf3eCMUKItJCwW4nAKLmJDoJTMXx6LsOGsBZHwPxV0LbR9titUhGpRCBor2nYs1EnN4qCd7f+3yU0lZ+dV5HdMWXesD2czEY8CTncEhD+6c4x3RnyLNC+zqHuM4U1szsQPkOxI5zqItxVgy0HmLThpaA0knohTVYAnq+Qhw+iA6yokRv/pBRTr9fPeUv03LBB5tYEhBDCkGICY4ZRuT+NlsBHMxAjeQIIYeOh0DwldEl2QXVJc3eNt5nkQw49BoCGIU=
                  dmartini@Davids-MacBook-Pro
          name: cloudinitdisk
        - dataVolume:
            name: idm-ldap-rootdisk-120en
          name: rootdisk

---
kind: Service
apiVersion: v1
metadata:
  name: idm-ldap
  namespace: openshift-vms
spec:
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
    - name: cokpit
      protocol: TCP
      port: 9090
      targetPort: 9090
    - name: ldap
      protocol: TCP
      port: 389
      targetPort: 389
    - name: ldap-https
      protocol: TCP
      port: 636
      targetPort: 636
  selector:
    kubevirt.io/domain: idm-ldap

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: idm-ldap
  namespace: openshift-vms
spec:
  host: idm.apps.ocp.drkspace.fr
  to:
    kind: Service
    name: idm-ldap
    weight: 100
  port:
    targetPort: cokpit
  tls:
    termination: passthrough
  wildcardPolicy: None